AutoRent.WebProject/Controllers/AuthenticationController.cs
using System.Web.Mvc;
using AutoRent.DAL.UnitOfWork;
using AutoRent.Validation;
using AutoRent.BaseService.Domain;
using AutoRent.UserServices.Domain;
using AutoRent.UserServices;
using AutoRent.RelationalServices.Domain.UserModel;

namespace AutoRent.Controllers
{
    public class AuthenticationController : Controller
    {
        public static BaseModel logged { get; private set; }
        public static bool IsLoggedAdmin { get; set; }

        private AdminService adminService;
        private UserService userService;
        private UnitOfWork unitOfWork = new UnitOfWork();

        public AuthenticationController()
        {
            userService = new UserService(unitOfWork, new ValidationDictionary(ModelState));
            adminService = new AdminService(unitOfWork, new ValidationDictionary(ModelState));
        }

        // GET: Authentication
        //User login form
        [HttpGet]
        public ActionResult UserLogIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UserLogIn(User user)
        {
            if (user.Email != null && user.Password != null)
            {
                User loggedUser = new User();
                
                loggedUser = userService.LogIn(user);

                if (loggedUser != null)
                {
                    Session["LogInData"] = loggedUser.Username;
                    logged = loggedUser;

                    return RedirectToAction("Index", "Home");
                }

                TempData["TextError"] = "Email or password were entered incorrectly";

                return View("UserLogIn");
            }

            return View("UserLogIn");
        }

        //Admin login form
        [HttpGet]
        public ActionResult AdminLogIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AdminLogIn(Admin admin)
        {
            if (admin.Email != null && admin.Password != null)
            {
                Admin loggedAdmin = new Admin();

                loggedAdmin = adminService.LogIn(admin);

                if (loggedAdmin != null)
                {
                    Session["LogInData"] = string.Format($"{loggedAdmin.FirstName} {loggedAdmin.LastName}");
                    logged = loggedAdmin;
                    IsLoggedAdmin = true;

                    return RedirectToAction("Index", "Home");
                }

                TempData["TextError"] = "Email or password were entered incorrectly";

                return View("AdminLogIn");
            }

            return View("AdminLogIn");
        }
        
        //Logout button
        public ActionResult LogOut()
        {
            Session.Clear();
            IsLoggedAdmin = false;
            logged = null;

            TempData["Information"] = "You have logged out successfully!";

            return RedirectToAction("Index", "Home");
        }
    }
}

AutoRent.WebProject/Controllers/UserController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoRent.DAL.UnitOfWork;
using AutoRent.Validation;
using AutoRent.Authorization;
using AutoRent.WebProject.ViewModels;
using AutoRent.RelationalServices.Domain.UserModel;
using AutoRent.UserServices;

namespace AutoRent.Controllers
{
    public class UserController : Controller
    {
        private UserService userService;

        public UserController()
        {
            userService = new UserService(new UnitOfWork(), new ValidationDictionary(ModelState));
        }

        // GET: User
        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Index()
        {
            return View(await userService.GetAllAsync());
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public ActionResult Details(int id)
        {
            User user = userService.Get(id);

            if (user == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(user);
        }

        //Gets the details for the logged user
        [HttpGet, AuthorizationActionFilter(true)]
        public ActionResult UserDetails()
        {
            User user = userService.Get(AuthenticationController.logged.Id);

            if (user == null)
            {
                return RedirectToAction("Error", "Home");
            }

            UserProfileViewModel userProfileViewModel = new UserProfileViewModel(
                user.Username, user.FirstName, 
                user.LastName, user.Email,
                user.BirthDate, user.PhoneNumber, 
                user.AdditionalInformation);

            return View(userProfileViewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(User user)
        {
            //Calls the validation method in the service
            userService.Validation(user);

            if (ModelState.IsValid)
            {
                if (userService.IsEmailEntered(user))
                {
                    TempData["EmailUser"] = "Email is alredy used, please choose another one!";
                    return View("Create");
                }

                userService.HashPassword(user);
                userService.Insert(user);

                await userService.SaveChangesAsync();
                TempData["Information"] = "You have successfully registed! Now please log in.";

                return RedirectToAction("Index", "Home");
            }

            return View("Create");
        }

        [HttpGet, AuthorizationActionFilter(true)]
        public async Task<ActionResult> Update(int id)
        {
            User user = userService.Get(id);

            userService.SetUserPasswordOnUpdate(user);

            //If user does not exsists
            if (user == null)
            {
                return RedirectToAction("Error", "Home");
            }

            if (!AuthenticationController.IsLoggedAdmin)
            {
                //If this is not this user's profile
                if (!await userService.IsUsersProfile(user, AuthenticationController.logged))
                {
                    return RedirectToAction("Error", "Home");
                }
            }

            return View(user);
        }
        [HttpPost]
        public async Task<ActionResult> Update(User user)
        {
            //Calls the validation method in the service
            userService.Validation(user);

            if (ModelState.IsValid)
            {
                userService.HashPassword(user);
                userService.Update(user);

                await userService.SaveChangesAsync();

                if (AuthenticationController.IsLoggedAdmin)
                {
                    return RedirectToAction("Index");
                }

                return RedirectToAction("UserDetails");
            }

            return View("Update");
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Delete(int id)
        {
            return View(await userService.GetAsync(u => u.Id == id));
        }
        [HttpPost]
        public async Task<ActionResult> Delete(User user)
        {
            userService.Delete(user);

            await userService.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

AutoRent.WebProject/Views/Authentication/AdminLogIn.cshtml
@model AutoRent.UserServices.Domain.Admin
@{
    ViewBag.Title = "Admin Log in";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="jumbotron" style="border-radius: 0; padding: 50px 0px; background-color: #1a1a1a; color: lightgrey; margin: 0">
    <div class="container">
        <h2 class="text-uppercase">Admin Log In</h2>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="margin: 95px 35px 50px 35px" align="center">
        <h2 style="margin-bottom: 25px">Log In</h2>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-12">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Email" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "Password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Log In" class="btn btn-default btn-lg" />
            </div>
        </div>

        <div>
            <p class="text-danger">@TempData["TextError"]</p>
        </div>
    </div>
}

<div align="center" style="margin: 30px 0 95px 0">
    <div>
        Back to user login:
        @Html.ActionLink("User Log In", "UserLogIn", "Authentication")
    </div>
</div>

AutoRent.WebProject/Views/Authentication/UserLogIn.cshtml
@model AutoRent.RelationalServices.Domain.UserModel.User
@{
    ViewBag.Title = "User Log in";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="jumbotron" style="border-radius: 0; padding: 50px 0px; background-color: #1a1a1a; color: lightgrey; margin: 0">
    <div class="container">
        <h2 class="text-uppercase">User Log In</h2>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="margin: 80px 35px 50px 35px" align="center">
        <h2 style="margin-bottom: 25px">Log In</h2>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-12">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Email" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "Password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Log In" class="btn btn-default btn-lg" />
            </div>
        </div>

        <div>
            <p class="text-danger">@TempData["TextError"]</p>
        </div>
    </div>
}

<div align="center" style="margin: 30px 0 80px 0">
    <div>
        You haven't got a registration:
        @Html.ActionLink("Register", "Create", "User")
    </div>
    <div style="margin-top: 10px">
        You are admin:
        @Html.ActionLink("Admin Log In", "AdminLogIn", "Authentication")
    </div>
</div>