AutoRent.WebProject/Controllers/AdminController.cs
using AutoRent.Authorization;
using AutoRent.Validation;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoRent.DAL.UnitOfWork;
using AutoRent.WebProject.ViewModels;
using AutoRent.UserServices.Domain;
using AutoRent.UserServices;

namespace AutoRent.Controllers
{
    public class AdminController : Controller
    {
        private AdminService adminService;

        public AdminController()
        {
            adminService = new AdminService(new UnitOfWork(), new ValidationDictionary(ModelState));
        }

        //GET: Admin
        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Index()
        {
            return View(await adminService.GetAllAsync());
        }

        [HttpGet]
        public ActionResult Profile()
        {
            int id = AuthenticationController.logged.Id;
            Admin admin = adminService.Get(id);
            AdminProfileViewModel adminProfileViewModel = new AdminProfileViewModel(admin.FirstName, admin.LastName, admin.Email);

            return View(adminProfileViewModel);
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Details(int id)
        {
            return View(await adminService.GetAsync(a => a.Id == id));
        }

        //Gets the details for the logged admin
        [HttpGet, AuthorizationActionFilter(true)]
        public ActionResult AdminDetails()
        {
            Admin admin = adminService.Get(AuthenticationController.logged.Id);

            if (admin == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(admin);
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(Admin admin)
        {
            //Calls the validation method in the service
            adminService.Validation(admin);

            if (ModelState.IsValid)
            {
                if (adminService.IsEmailEntered(admin))
                {
                    TempData["EmailAdmin"] = "Email is alredy used, please choose another one!";
                    return View("Create");
                }

                adminService.HashPassword(admin);
                adminService.Insert(admin);
                await adminService.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View("Create");
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Update(int id)
        {
            Admin admin = await adminService.GetAsync(a => a.Id == id);
            adminService.SetAdminPasswordOnUpdate(admin);

            return View(admin);
        }
        [HttpPost]
        public async Task<ActionResult> Update(Admin admin)
        {
            //Calls the validation method in the service
            adminService.Validation(admin);

            if (ModelState.IsValid)
            {
                adminService.HashPassword(admin);
                adminService.Update(admin);
                await adminService.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View("Update");
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Delete(int id)
        {
            return View(await adminService.GetAsync(a => a.Id == id));
        }
        [HttpPost]
        public async Task<ActionResult> Delete(Admin admin)
        {
            adminService.Delete(admin);

            await adminService.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

AutoRent.WebProject/Controllers/CarController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoRent.DAL.UnitOfWork;
using AutoRent.Validation;
using AutoRent.Authorization;
using AutoRent.CarServices;
using AutoRent.RelationalServices.Domain.CarModel;

namespace AutoRent.Controllers
{
    public class CarController : Controller
    {
        private CarService carService;

        public CarController()
        {
            carService = new CarService(new UnitOfWork(), new ValidationDictionary(ModelState));
        }

        // GET: Car
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await carService.GetAllAsync());
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            Car car = carService.Get(id);

            if (car == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(car);
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(Car car)
        {
            if (ModelState.IsValid)
            {
                carService.Insert(car);
                await carService.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View("Create");
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Update(int id)
        {
            return View(await carService.GetAsync(c => c.Id == id));
        }
        [HttpPost]
        public async Task<ActionResult> Update(Car car)
        {
            if (ModelState.IsValid)
            {
                carService.Update(car);
                await carService.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View("Update");
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Delete(int id)
        {
            return View(await carService.GetAsync(c => c.Id == id));
        }
        [HttpPost]
        public async Task<ActionResult> Delete(Car car)
        {
            //Calls the SetAllReferencesToNullWhenDeleted() method in the service
            carService.SetAllReferencesToNullWhenDeleted(car);
            carService.Delete(car);

            await carService.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

AutoRent.WebProject/Controllers/CarRentController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoRent.DAL.UnitOfWork;
using AutoRent.Validation;
using AutoRent.Authorization;
using AutoRent.CarServices;
using AutoRent.RelationalServices.Domain.CarModel;
using AutoRent.RelationalServices.Domain.UserModel;

namespace AutoRent.Controllers
{
    public class CarRentController : Controller
    {
        private CarRentService carRentService;

        public CarRentController()
        {
            carRentService = new CarRentService(new UnitOfWork(), new ValidationDictionary(ModelState));
        }

        // GET: CarRent
        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Index()
        {
            return View("ListAllCarRents", await carRentService.GetAllAsync());
        }

        [HttpGet, AuthorizationActionFilter(true)]
        public async Task<ActionResult> Details(int id)
        {
            CarRent carRent = carRentService.Get(id);
            //If payment does not exsists
            if (carRent == null)
            {
                return RedirectToAction("Error", "Home");
            }

            if (!AuthenticationController.IsLoggedAdmin)
            {
                //If this is not this user's payment
                if (!await carRentService.IsUsersCarRent(carRent, AuthenticationController.logged))
                {
                    return RedirectToAction("Error", "Home");
                }
            }

            return View(carRent);
        }

        [HttpGet, AuthorizationActionFilter(true)]
        public async Task<ActionResult> ListCurrentUserCarRents()
        {
            return View("Index", await carRentService.GetAllAsync(p => p.UserId == AuthenticationController.logged.Id));
        }

        [HttpGet, AuthorizationActionFilter(true)]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(CarRent carRent, int id)
        {
            carRent.CarId = id;

            if (carRentService.CheckIfCarAmountIsZero(id))
            {
                return RedirectToAction("EmptyCarAmount", "Home");
            }

            if (carRentService.CheckIfMainPaymentIsNotSet((User)AuthenticationController.logged))
            {
                TempData["Payment"] = "You have to set a main payment method";

                return View("Create");
            }

            //Calls the validation method in the service
            carRentService.Validation(carRent);

            if (ModelState.IsValid)
            {
                carRent.UserId = AuthenticationController.logged.Id;

                carRentService.CalculateTotalPrice(carRent);

                carRentService.ReduceTheNumberOfAvaliableCars(carRent);

                carRentService.Insert(carRent);

               await carRentService.SaveChangesAsync();

                if (AuthenticationController.IsLoggedAdmin)
                {
                    return RedirectToAction("ListCurrentAdminCarRents");
                }

                return RedirectToAction("ListCurrentUserCarRents");
            }
            return View("Create");
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Update(int id)
        {
            TempData["CarRentId"] = id;
            return View(await carRentService.GetAsync(cr => cr.Id == id));
        }
        [HttpPost]
        public async Task<ActionResult> Update(CarRent carRent)
        {
            //Calls the validation method in the service
            carRentService.Validation(carRent);

            //Sets the CarRent to the original owner properties after update
            carRentService.SetCarRentPropertiesOnUpdate(carRent, int.Parse(TempData["CarRentId"].ToString()));

            if (ModelState.IsValid)
            {
                carRentService.Update(carRent);

                await carRentService.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View("Update");
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Delete(int id)
        {
            return View(await carRentService.GetAsync(cr => cr.Id == id));
        }
        [HttpPost]
        public async Task<ActionResult> Delete(CarRent carRent)
        {
            carRentService.Delete(carRent);

            await carRentService.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

AutoRent.WebProject/Controllers/UserController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoRent.DAL.UnitOfWork;
using AutoRent.Validation;
using AutoRent.Authorization;
using AutoRent.WebProject.ViewModels;
using AutoRent.RelationalServices.Domain.UserModel;
using AutoRent.UserServices;

namespace AutoRent.Controllers
{
    public class UserController : Controller
    {
        private UserService userService;

        public UserController()
        {
            userService = new UserService(new UnitOfWork(), new ValidationDictionary(ModelState));
        }

        // GET: User
        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Index()
        {
            return View(await userService.GetAllAsync());
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public ActionResult Details(int id)
        {
            User user = userService.Get(id);

            if (user == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(user);
        }

        //Gets the details for the logged user
        [HttpGet, AuthorizationActionFilter(true)]
        public ActionResult UserDetails()
        {
            User user = userService.Get(AuthenticationController.logged.Id);

            if (user == null)
            {
                return RedirectToAction("Error", "Home");
            }

            UserProfileViewModel userProfileViewModel = new UserProfileViewModel(
                user.Username, user.FirstName, 
                user.LastName, user.Email,
                user.BirthDate, user.PhoneNumber, 
                user.AdditionalInformation);

            return View(userProfileViewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(User user)
        {
            //Calls the validation method in the service
            userService.Validation(user);

            if (ModelState.IsValid)
            {
                if (userService.IsEmailEntered(user))
                {
                    TempData["EmailUser"] = "Email is alredy used, please choose another one!";
                    return View("Create");
                }

                userService.HashPassword(user);
                userService.Insert(user);

                await userService.SaveChangesAsync();
                TempData["Information"] = "You have successfully registed! Now please log in.";

                return RedirectToAction("Index", "Home");
            }

            return View("Create");
        }

        [HttpGet, AuthorizationActionFilter(true)]
        public async Task<ActionResult> Update(int id)
        {
            User user = userService.Get(id);

            userService.SetUserPasswordOnUpdate(user);

            //If user does not exsists
            if (user == null)
            {
                return RedirectToAction("Error", "Home");
            }

            if (!AuthenticationController.IsLoggedAdmin)
            {
                //If this is not this user's profile
                if (!await userService.IsUsersProfile(user, AuthenticationController.logged))
                {
                    return RedirectToAction("Error", "Home");
                }
            }

            return View(user);
        }
        [HttpPost]
        public async Task<ActionResult> Update(User user)
        {
            //Calls the validation method in the service
            userService.Validation(user);

            if (ModelState.IsValid)
            {
                userService.HashPassword(user);
                userService.Update(user);

                await userService.SaveChangesAsync();

                if (AuthenticationController.IsLoggedAdmin)
                {
                    return RedirectToAction("Index");
                }

                return RedirectToAction("UserDetails");
            }

            return View("Update");
        }

        [HttpGet, AuthorizationActionFilter(false)]
        public async Task<ActionResult> Delete(int id)
        {
            return View(await userService.GetAsync(u => u.Id == id));
        }
        [HttpPost]
        public async Task<ActionResult> Delete(User user)
        {
            userService.Delete(user);

            await userService.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

AutoRent.WebProject/Views/Shared/_HeaderNavigationBar.cshtml
@using AutoRent.Controllers
<div class="navbar navbar-inverse navbar-fixed-top" style="font-family: 'Montserrat', sans-serif;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("AutoRent", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Cars", "Index", "Car")</li>
                @if (AuthenticationController.IsLoggedAdmin)
                 {
                    <li>@Html.ActionLink("All Payments", "Index", "Payment")</li>
                    <li>@Html.ActionLink("All Users", "Index", "User")</li>
                    <li>@Html.ActionLink("All CarRents", "Index", "CarRent")</li>
                    <li>@Html.ActionLink("All Admins", "Index", "Admin")</li>
                    <li>@Html.ActionLink("Profile", "Profile", "Admin")</li>
                }
                else if(AuthenticationController.logged != null)
                {
                    <li>@Html.ActionLink("Payment", "ListCurrentUserPayments", "Payment")</li>
                    <li>@Html.ActionLink("Profile", "UserDetails", "User")</li>
                    <li>@Html.ActionLink("Car Rents", "ListCurrentUserCarRents", "CarRent")</li>
                }
                <li>@Html.ActionLink("News", "News", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contacts", "Contacts", "Home")</li>
            </ul>

            <!-- Right align navbar in the navbar -->
            <ul class="nav navbar-nav navbar-right">
                @if (Session["LogInData"] != null)
                {
                    <li>@Html.ActionLink("Log Out", "LogOut", "Authentication")</li>
                    <li>
                        <span class="navbar-text">Hello, @Session["LogInData"]</span>
                    </li>
                }           
                else
                {
                    <li>@Html.ActionLink("Log In", "UserLogIn", "Authentication")</li>
                }
            </ul>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

AutoRent.WebProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AutoRent</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans" rel="stylesheet">
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <style>
        h1, h2, h3{
            font-family: 'Montserrat', sans-serif;
        }
        p, span, blockquote {
            font-family: 'Open Sans', sans-serif;
        }
        p {
            line-height: 23px;
        }
    </style>
</head>
<body style="padding-bottom: 0;">

    @{
        Html.RenderPartial("_HeaderNavigationBar");
    }

    <div class="container-fluid body-content" style="padding-left: 0; padding-right: 0">
        <span class="text-info" style="margin-top:15px">@TempData["Information"]</span>

        @RenderBody()

        <footer align ="center" style="padding: 30px 0; background-color: #595959; color: #ffffff">
            <p>&copy; AutoRent - New Automobile Renting Service </p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script>
        $(function () {
            $("#datetimepicker").datetimepicker({
                format: 'DD/MMM/YYYY'
            });

            $("#StartDate").datetimepicker({
                format: 'DD/MMM/YYYY'
            });

            $("#EndDate").datetimepicker({
                format: 'DD/MMM/YYYY'
            });
        });
    </script>
</body>
</html>